on:
  push:
    branches: [sm/gha]

jobs:
  check:
    strategy:
      matrix:
        # runs-on: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: [ubuntu-latest]
        # cli: [sfdx, sf]
        cli: [sfdx]
        # method: [tarball, npm, installer]
        method: [tarball]
        # channel: [stable, stable-rc]
        channel: [stable]
        exclude:
          - runs-on: ubuntu-latest
            method: installer
      fail-fast: false
    uses: ./.github/workflows/install.yml
    with:
      method: ${{ matrix.method }}
      cli: ${{ matrix.cli }}
      channel: ${{ matrix.channel }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit
