on:
  push:
    branches: [sm/gha]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        # runs-on: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: [ubuntu-latest]
        cli: [sfdx, sf]
        method: [tarball, npm, installer]
    uses: ./.github/workflows/install.yml
    with:
      method: tarball
      cli: ${{ matrix.cli }}
      channel: latest
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit
