on:
  push:
    branches: [sm/gha]

jobs:
  check:
    strategy:
      matrix:
        # runs-on: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: [ubuntu-latest]
        # cli: [sfdx, sf]
        cli: [sfdx]
        # method: [tarball, npm, installer]
        method: [tarball]
        # channel: [stable, stable-rc]
        channel: [stable]
        exclude:
          - runs-on: ubuntu-latest
            method: installer
      fail-fast: false
    uses: ./.github/workflows/install.yml
    with:
      method: ${{ matrix.method }}
      cli: ${{ matrix.cli }}
      channel: ${{ matrix.channel }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit
  report:
    # strategy:
    #   matrix:
    #     # runs-on: [ubuntu-latest, windows-latest, macos-latest]
    #     runs-on: [windows-latest, ubuntu-latest]
    #     cli: [sfdx, sf]
    #     method: [tarball, npm, installer]
    #     channel: [stable, stable-rc]
    #     exclude:
    #       - runs-on: ubuntu-latest
    #         method: installer
    #   fail-fast: false
    runs-on: ubuntu-latest
    needs: check
    steps:
      - run: |
          git clone https://github.com/heroku/heroku-buildpack-l2met-shuttle.git
          heroku-buildpack-l2met-shuttle/bin/compile .
          # heroku-buildpack-l2met-shuttle/support/start-l2met-shuttle echo "count#$base.success=$status"
      - run: echo ${{ needs.check }}
