on:
  push:
    branches: [sm/gha]

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        # runs-on: [ubuntu-latest, windows-latest, macos-latest]
        runs-on: [ubuntu-latest]
        cli: [sfdx, sf]
        method: [tarball, npm, installer]
        channel: [stable, stable-rc]
    uses: ./.github/workflows/install.yml
    with:
      method: ${{ matrix.method }}
      cli: ${{ matrix.cli }}
      channel: ${{ matrix.channel }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit
