on:
  push:
    branches: [sm/gha]
  schedule:
    - cron: 7 4 * * *
jobs:
  check:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
        cli: [sfdx, sf]
        method: [tarball, npm, installer]
        channel: [stable, stable-rc]
        exclude:
          - runs-on: ubuntu-latest
            method: installer
      fail-fast: false
    uses: ./.github/workflows/install.yml
    with:
      method: ${{ matrix.method }}
      cli: ${{ matrix.cli }}
      channel: ${{ matrix.channel }}
      runs-on: ${{ matrix.runs-on }}
    secrets: inherit
