on:
  workflow_call:
    inputs:
      metricName:
        required: true
        type: string
      metricValue:
        required: true
        type: string

jobs:
  report:
    runs-on: ubuntu-latest
    env:
      L2MET_SHUTTLE_URL: ${{ secrets.L2MET_SHUTTLE_URL }}
    steps:
      - run: |
          git clone https://github.com/heroku/heroku-buildpack-l2met-shuttle.git
          heroku-buildpack-l2met-shuttle/bin/compile .
      - run: heroku-buildpack-l2met-shuttle/support/start-l2met-shuttle echo "${{ inputs.metricName }}=0"
        if: ${{inputs.metricValue == "Failed"}}
      - run: heroku-buildpack-l2met-shuttle/support/start-l2met-shuttle echo "${{ inputs.metricName }}=1"
        if: ${{inputs.metricValue == "Passed"}}
